name: demo

on:

- push
jobs: 
build: 
runs-on: ubuntu-latest
steps:
-  name: List Files
   run: |
      echo $GITHUB_SHA
      echo $GITHUB_REPOSITORY
      echo $GITHUB_WORKSPACE


      echo "${{ github.token }}"