# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: List Files
      run: |
         pwd
         ls -a
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         echo "${{ github.token }}"
         
    - name: Step 1 - Downloads a copy of your repository on the runner.
      uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
   # - name: Step 4 - Publish to GitHub Packages Apache Maven
    #  run: mvn -B deploy
     # env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
